adresse_index:
    path:     /
    defaults: { _controller: "BackOfficeBundle:Adresse:index" }
    methods:  GET

adresse_show:
    path:     /{id_adresse}/show
    defaults: { _controller: "BackOfficeBundle:Adresse:show" }
    methods:  GET

adresse_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:Adresse:new" }
    methods:  [GET, POST]

adresse_edit:
    path:     /{id_adresse}/edit
    defaults: { _controller: "BackOfficeBundle:Adresse:edit" }
    methods:  [GET, POST]

adresse_delete:
    path:     /{id_adresse}/delete
    defaults: { _controller: "BackOfficeBundle:Adresse:delete" }
    methods:  DELETE
