commentaire_index:
    path:     /
    defaults: { _controller: "BackOfficeBundle:Commentaire:index" }
    methods:  GET

commentaire_show:
    path:     /{id_com}/show
    defaults: { _controller: "BackOfficeBundle:Commentaire:show" }
    methods:  GET

commentaire_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:Commentaire:new" }
    methods:  [GET, POST]

commentaire_edit:
    path:     /{id_com}/edit
    defaults: { _controller: "BackOfficeBundle:Commentaire:edit" }
    methods:  [GET, POST]

commentaire_delete:
    path:     /{id_com}/delete
    defaults: { _controller: "BackOfficeBundle:Commentaire:delete" }
    methods:  DELETE
