note_index:
    path:     /
    defaults: { _controller: "BackOfficeBundle:Note:index" }
    methods:  GET

note_show:
    path:     /{id_note}/show
    defaults: { _controller: "BackOfficeBundle:Note:show" }
    methods:  GET

note_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:Note:new" }
    methods:  [GET, POST]

note_edit:
    path:     /{id_note}/edit
    defaults: { _controller: "BackOfficeBundle:Note:edit" }
    methods:  [GET, POST]

note_delete:
    path:     /{id_note}/delete
    defaults: { _controller: "BackOfficeBundle:Note:delete" }
    methods:  DELETE
