notification_index:
    path:     /
    defaults: { _controller: "BackOfficeBundle:Notification:index" }
    methods:  GET

notification_show:
    path:     /{id_notif}/show
    defaults: { _controller: "BackOfficeBundle:Notification:show" }
    methods:  GET

notification_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:Notification:new" }
    methods:  [GET, POST]

notification_edit:
    path:     /{id_notif}/edit
    defaults: { _controller: "BackOfficeBundle:Notification:edit" }
    methods:  [GET, POST]

notification_delete:
    path:     /{id_notif}/delete
    defaults: { _controller: "BackOfficeBundle:Notification:delete" }
    methods:  DELETE
